repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json

  - repo: local
    hooks:
      - id: format
        name: Format code with Black and isort
        entry: make format
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: Lint with flake8
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
